title: Zihan Wang # your name (or website title) here
logo: "/images/zihan.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Master in Financial Engineering 
  <br><br>
  Columbia University 
  <br><br>
  <a href="https://www.linkedin.com/in/zihan-wang-ab9176152/">View My LinkedIn Profile</a> 

social-network-links:
  email: "Zihan Wang"
  github: zihan23
  linkedin: zihan-wang

share-links-active:
  linkedin: true
theme: jekyll-theme-minimal

